name: applying
on:  
  # pull_request:
  #   branches:
  #     - main
  # push:
  #   branches:
  #     - main
  workflow_dispatch:
jobs:
  job-make-infra:
    runs-on : ubuntu-latest

    steps: 
      - name: "Setup - Checkout"
        uses: actions/checkout@v2.1.0

      - name: "Setup - Terraform CLI"
        uses: hashicorp/setup-terraform@v1
        # with:
        #  api_key: ${{ secrets.NEW_RELIC_API_KEY }}
        #  account_id: ${{ secrets.NEW_RELIC_ACCOUNT_ID }}

      - name: terraform init
        run: |
          cd dashboard
          terraform init 
      - name: terraform plan 
        run: |
          cd dashboard
          terraform plan
        
      - name: terraform apply
        run: |
          cd dashboard
          terraform apply -auto-approve
    