name: applying
on:  
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  job-make-infra:
    runs-on : ubuntu-latest

    steps: 
      - name: "Setup - Checkout"
        uses: actions/checkout@v2.1.0

      # - uses: actions/checkout@v3
      - name: "Setup - Terraform CLI"
        uses: hashicorp/setup-terraform@v1
         with:
         NEW_RELIC_API_KEY: ${{ secrets.NEW_RELIC_API_KEY }}
         NEW_RELIC_ACCOUNT_ID: ${{ secrets.NEW_RELIC_ACCOUNT_ID }}
      - name: terraform init
        run: |
          cd dashboard
          terraform init 
      - name: terraform plan & apply
        run: |
          cd dashboard
          terraform plan
          terraform apply -auto-approve
    # env:
    #       NEW_RELIC_ACCOUNT_ID: ${{ secrets.NEW_RELIC_ACCOUNT_ID }}
    #       NEW_RELIC_API_KEY: ${{ secrets.NEW_RELIC_API_KEY }}